# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OrXXEX3ECZsDve2oLQpZpJIuNb8UwLgl
"""

# get OpenNMT
from google.colab import drive
drive.mount('/content/gdrive')
!ls
!git clone -b v1.2.0 https://github.com/OpenNMT/OpenNMT-py.git
!git pull

!pip install -r ./OpenNMT-py/floyd_requirements.txt

!unzip data.zip
!unzip preprocessed_data.zip

# BPE
!mkdir BPE
!python OpenNMT-py/tools/learn_bpe.py -i preprocessed_data/train.en -o BPE/src.code -s 10000
!python OpenNMT-py/tools/learn_bpe.py -i preprocessed_data/train.fa -o BPE/tgt.code -s 10000
!python OpenNMT-py/tools/apply_bpe.py -c BPE/src.code -i preprocessed_data/train.en -o BPE/train-bpe.en
!python OpenNMT-py/tools/apply_bpe.py -c BPE/src.code -i preprocessed_data/valid.en -o BPE/valid-bpe.en
!python OpenNMT-py/tools/apply_bpe.py -c BPE/src.code -i preprocessed_data/test.en -o BPE/test-bpe.en.txt
!python OpenNMT-py/tools/apply_bpe.py -c BPE/tgt.code -i preprocessed_data/train.fa -o BPE/train-bpe.fa
!python OpenNMT-py/tools/apply_bpe.py -c BPE/tgt.code -i preprocessed_data/valid.fa -o BPE/valid-bpe.fa
!python OpenNMT-py/tools/apply_bpe.py -c BPE/tgt.code -i preprocessed_data/test.fa -o BPE/test-bpe.fa

# Preprocess
!pip install torchtext==0.4
!pip install configargparse
!mkdir translate

!python OpenNMT-py/preprocess.py -train_src BPE/train-bpe.en -train_tgt BPE/train-bpe.fa -valid_src BPE/valid-bpe.en -valid_tgt BPE/valid-bpe.fa -save_data translate/data -overwrite

"""### train"""

# Train
!python OpenNMT-py/train.py -data translate/data -save_model translate/model -train_steps 50000 -save_checkpoint_steps 5000 -valid_steps 1000 -world_size 1 -gpu_rank 0

# Test
!mkdir pred
!mkdir pred/test
!mkdir pred/validation

from tqdm import tqdm

bleus = []
for i in tqdm(range(5000,50001,5000)) :
  c1 = !python OpenNMT-py/translate.py -model translate/model_step_{i}.pt -src data/valid.en -output pred/validation/pred_valid_{i}.txt -replace_unk
  c2 = !sed -i "s/@@ //g"  pred/validation/pred_valid_{i}.txt
  c3 = !perl OpenNMT-py/tools/multi-bleu.perl data/valid.fa < pred/validation/pred_valid_{i}.txt
  bleus.append(c3)

bleus

!python OpenNMT-py/translate.py -model translate/model_step_50000.pt -src data/test.en -output pred/test/pred_test.txt -replace_unk -verbose

!sed -i "s/@@ //g"  pred/test/pred_test.txt

!perl OpenNMT-py/tools/multi-bleu.perl data/test.fa < pred/test/pred_test.txt